### PR TITLE
Bugfix - Negotation message payload offset zero values

### PR DESCRIPTION
**Pull request by Rican7**
This is the kind of PR that I just hate writing. I don't want to write this, because it shouldn't exist. But, "C'est la vie".

Anyway, this PR introduces a change that purposefully breaks spec by sending up zero values for the payload offsets of the domain name and hostname. This is necessary as some NTLM servers expect a zero offset denotion when the negotiation flags don't include the flags for supplying the domain and workstation payload data. [Even though the specification says otherwise](https://msdn.microsoft.com/en-us/library/cc236641.aspx):

> Otherwise, if the NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED flag is not set in NegotiateFlags, indicating that a DomainName is not supplied in Payload, the fields take the following values, and MUST be ignored upon receipt.
> - DomainNameLen and DomainNameMaxLen fields SHOULD be set to zero.
> - DomainNameBufferOffset field SHOULD be set to the offset from the beginning of the NEGOTIATE_MESSAGE to where the DomainName would be in Payload if it was present.

---

> Otherwise, if the NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED flag is not set in NegotiateFlags, indicating that a WorkstationName is not supplied in Payload, the fields take the following values, and MUST be ignored upon receipt.
> - WorkstationLen and WorkstationMaxLen fields SHOULD be set to zero.
> - WorkstationBufferOffset field SHOULD be set to the offset from the beginning of the NEGOTIATE_MESSAGE to where the WorkstationName would be in Payload if it was present.

This is [what cURL does](https://github.com/bagder/curl/blob/curl-7_46_0/lib/curl_ntlm_msgs.c#L364-L370), so it's seemingly safe here. :disappointed:

### CODE REVIEW

**Comment by brianmuse** [comment]
Was this tested for law-abiding citizens as well as the servers you mention that implement the spec incorrectly?

**Comment by Rican7** [comment]
@brianmuse yup! Testing beyond the negotiation message was limited due to lack of test credentials on quite a few example systems, but the negotiation message is the unit at play here anyway.

**Comment by brianmuse** [comment]
Thanks for the inline docs and all the links to the relevant articles and resources. This change makes at least a little bit of sense, given it's what CURL does as well. Too bad it's necessary, but great work on the fix! :+1:

**Comment by Rican7** [comment]
Ha, thanks! :smiley: 

And yea, I knew this would be a "wtf?" unless I put in quite a bit of docs explaining it. :stuck_out_tongue_closed_eyes:

**Comment by jstruzik** [comment]
I think the biggest thing to highlight in this PR is how the spec states that even if the offset values are set, they must be completely ignored.

Anyway, LGTM :+1: Good work on the research and documenting the spec.

**Comment by Rican7** [comment]
> I think the biggest thing to highlight in this PR is how the spec states that even if the offset values are set, they must be completely ignored.

Yup, if only the actual implementations worked that way. :disappointed: 

Thanks for the merge!

**Pull request merged**
